PP-5051 Added library for Java 11
- Container starts with following warning but works fine and passes end to end tests
   java.lang.ClassNotFoundException: javax.xml.bind.JAXBContex
- Added dependency missing for Jersey library for above warning